### PR TITLE
feat!: remove deprecated append method in StreamWriterV2

### PR DESCRIPTION
**Pull request by yayi-google**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquerystorage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

### CODE REVIEW

**Review by bigang-li — APPROVED** [review]

**Review by yirutang — APPROVED** [review]

**Comment by stephaniewang526** [comment]
Hi @yayi-google -- the change is fine but the PR needs to be `feat!: ` since it indicates a major breaking change.

Please update both the PR subject **and** the initial commit (which will be used in the release notes).

**Comment by yayi-google** [comment]
> Hi @yayi-google -- the change is fine but the PR needs to be `feat!: ` since it indicates a major breaking change.
> 
> Please update both the PR subject **and** the initial commit (which will be used in the release notes).

Done. Thank you!

**Comment by stephaniewang526** [comment]
Also this is breaking binary compat:
```
Error:  7002: com.google.cloud.bigquery.storage.v1beta2.StreamWriterV2: Method 'public com.google.api.core.ApiFuture append(com.google.cloud.bigquery.storage.v1beta2.AppendRowsRequest)' has been removed
```
To fix this, we need to modify this [file](https://github.com/googleapis/java-bigquerystorage/blob/master/google-cloud-bigquerystorage/clirr-ignored-differences.xml) -- we can delete these once the client is released (meaning new baseline is established for binary compat check).

**Comment by yayi-google** [comment]
Done. Thank you!

**Review by stephaniewang526 — APPROVED** [review]

**Pull request merged**
